package modelo.entidades;
// Generated 3 feb. 2021 9:55:59 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Autor generated by hbm2java
 */
public class Autor implements java.io.Serializable {

	private int idAutor;
	private String nombre;
	private String apellidos;
	private Set autorlibros = new HashSet(0);

	public Autor() {
	}

	public Autor(int idAutor) {
		this.idAutor = idAutor;
	}

	public Autor(int idAutor, String nombre, String apellidos, Set autorlibros) {
		this.idAutor = idAutor;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.autorlibros = autorlibros;
	}

	public int getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(int idAutor) {
		this.idAutor = idAutor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Set getAutorlibros() {
		return this.autorlibros;
	}

	public void setAutorlibros(Set autorlibros) {
		this.autorlibros = autorlibros;
	}

}
