package modelo.entidades;
// Generated 3 feb. 2021 9:55:59 by Hibernate Tools 5.2.12.Final

/**
 * Autorlibro generated by hbm2java
 */
public class Autorlibro implements java.io.Serializable {

	private int idAutorLibro;
	private Autor autor;
	private Libro libro;

	public Autorlibro() {
	}

	public Autorlibro(int idAutorLibro, Autor autor, Libro libro) {
		this.idAutorLibro = idAutorLibro;
		this.autor = autor;
		this.libro = libro;
	}

	public int getIdAutorLibro() {
		return this.idAutorLibro;
	}

	public void setIdAutorLibro(int idAutorLibro) {
		this.idAutorLibro = idAutorLibro;
	}

	public Autor getAutor() {
		return this.autor;
	}

	public void setAutor(Autor autor) {
		this.autor = autor;
	}

	public Libro getLibro() {
		return this.libro;
	}

	public void setLibro(Libro libro) {
		this.libro = libro;
	}

}
